name: Makefile CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v3    
    - name: Run test
      run: make test
